### PR TITLE
updating max piece size to 32mb

### PR DESCRIPTION
**Pull request by WhyNoobMaster69IsNotAvailable**

### CODE REVIEW

**Comment by rndusr** [comment]
Why?

**Comment by WhyNoobMaster69IsNotAvailable** [comment]
When creating torrents for large about of data, say 80 to 200 gigs, using 16mb as the piece size just won't cut it. With 16mb piece size, users will end up with 200-300kb size torrents with 50k+ pieces. 

With 32mb piece size, the overall size, and number of pieces will come down dramatically. and all torrent clients supports 32mb piece sizes. 

there are few that supports 64mb and 128 in some cases, but that's not needed.

**Comment by WhyNoobMaster69IsNotAvailable** [comment]
certain places will not accept torrents if they have lots of pieces in them.

**Comment by rndusr** [comment]
And certain places won't accept them if they are too big.

I recommend to use a subclass that overloads piece_size_max.

**Pull request closed without merging**
